### ISSUE TITLE
Fix the default endpoint of graphql to /connect

### ISSUE THREAD

**Issue by aseaday** [cyberconnecthq/cyberconnect-docs-v2#8]
Hi, I found your playground has a wrong endpoint may cause the inconvenience to the users or developers. But it could fixed by modify the component props endpoint. I also could help you fix it.

**Comment by HaoPeiwen** [comment]
Thank you very much for your feedback. We have solved this problem in the latest version and upgraded the playground to [v1.5.16](https://github.com/99designs/gqlgen/blob/v0.15.0/graphql/playground/playground.go#L60).
